/*
 * ultrasonic.c
 *
 *  Created on: Oct 19, 2023
 *      Author: shredan abdullah
 */

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"

uint8 g_edgeCount=0;
uint8 g_check=0;
uint16 g_totalHighTime=0;


/*• Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver.*/
void Ultrasonic_init(void){
	/* Create configuration structure for ICU driver */
		ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};
    /* Initialize both the ICU driver */
		ICU_init(&ICU_Configurations);
	/* Set the Call back function pointer in the ICU driver */
		ICU_setCallBack(Ultrasonic_edgeProcessing);
	/* Setup the direction for the trigger pin as output pin through the GPIO driver.*/
		GPIO_setupPinDirection(ULTRASONIC_TRIG_PORT , ULTRASONIC_TRIG_PIN,  PIN_OUTPUT);
		GPIO_writePin (ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, LOGIC_LOW);/* initially zero*/
}
/*• Description
➢ Send the Trigger pulse to the ultrasonic.*/
void Ultrasonic_Trigger(void){
	uint8 count=0;
	/*We need to transmit trigger pulse of at least 10 us to the HC-SR04 Trig Pin.*/
	while(count < 11){ /*11 not 10 to compensate time taken to execute uint8 count=0;*/
		count++;
		GPIO_writePin( ULTRASONIC_TRIG_PORT,  ULTRASONIC_TRIG_PIN,  LOGIC_HIGH);
	}
	GPIO_writePin( ULTRASONIC_TRIG_PORT,  ULTRASONIC_TRIG_PIN,  LOGIC_LOW);
}
/*• Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.*/


uint16 Ultrasonic_readDistance(void){
	uint16 Total_Distance=0;
	Ultrasonic_Trigger();
	if(g_check==1){
		g_check=0;
		/*At 28 degrees Celsius, the speed of sound in dry air is approximately 348.2 meters per second.
		 * (348.2 * 1e-6 * 100) / 2.0 calculates to approximately 0.01741
		 * */
		Total_Distance=(uint16)(g_totalHighTime *  0.01741);//(g_totalHighTime*17000);
	}
	return Total_Distance;
}


/*• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	switch(g_edgeCount){
		case 1:
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			ICU_clearTimerValue();
			/* Detect falling edge */
			ICU_setEdgeDetectionType(FALLING);
			break;
		case 2:
			/* Store the High time value */
			g_totalHighTime = ICU_getInputCaptureValue();
			/* Detect rising edge */
			ICU_setEdgeDetectionType(RAISING);
			g_check=1;
			break;
	}
}
