/*
 * ultrasonic.c
 *
 *  Created on: Oct 19, 2023
 *      Author: Tobi
 */
#include "common_macros.h" /* For GET_BIT Macro */
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"

/*• Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver.*/
void Ultrasonic_init(void){
	/* Create configuration structure for ICU driver */
		ICU_ConfigType ICU_Configurations = {F_CPU_CLOCK,RAISING};
    /* Initialize both the ICU driver */
		ICU_init(&ICU_Configurations);
	/* Set the Call back function pointer in the ICU driver */
		ICU_setCallBack(Ultrasonic_edgeProcessing);
	/* Setup the direction for the trigger pin as output pin through the GPIO driver.*/
		GPIO_setupPinDirection(PORTB_ID , PIN5_ID,  PIN_OUTPUT);
}
/*• Description
➢ Send the Trigger pulse to the ultrasonic.*/
void Ultrasonic_Trigger(void){

}
/*• Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.*/
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	return ;
}


/*• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			ICU_clearTimerValue();
			/* Detect falling edge */
			ICU_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = ICU_getInputCaptureValue();
			/* Detect rising edge */
			ICU_setEdgeDetectionType(RAISING);
		}
		else if(g_edgeCount == 3)
		{
			/* Store the Period time value */
			g_timePeriod = ICU_getInputCaptureValue();
			/* Detect falling edge */
			ICU_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 4)
		{
			/* Store the Period time value + High time value */
			g_timePeriodPlusHigh = ICU_getInputCaptureValue();
			/* Clear the timer counter register to start measurements again */
			ICU_clearTimerValue();
			/* Detect rising edge */
			ICU_setEdgeDetectionType(RAISING);
		}
}
